spring:
  application:
    name: Cinema-Management
  datasource:
    url: jdbc:mysql://localhost:3306/cimena-management
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

# Image size
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: /api/v1
# Path folder static
upload-path: src/main/resources/static

# Jwt
jwt:
  expiration: 86400000 # (24 * 60 * 60 * 1000 mls)
  secretKey: XeKCntPJuk/iJoaxpv9ifO4aj+6TXWpL123R9b47aqH0=
