spring:
  application:
    name: Cinema-Management
  datasource:
    url: jdbc:mysql://localhost:3306/cimena-management
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

#Image size
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Path folder static
#upload-path=src/main/resources/static